sudo: required
services:
  - docker
before_install:
  - docker build -t markbojesen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true markbojesen/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-eu-north-1-014376225706"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"